// src/modules/x-chat/components/chat-client.vue
<template>
    <form class="chat-form" v-on:submit="onSubmit" >
        <div class="form-group">
            <label for="name">name:</label>
            <input
                id="name"
                type="text"
                class="form-control"
                required
                v-model="name"
            >
        </div>
        <div class="form-group" >
            <label for="text">text</label>
            <textarea
                name="text"
                id="text"
                cols="30"
                rows="10"
                class="form-control"
                required
                v-model="text"
            ></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</template>

<script>
    import {store} from "~/store";
    import {xChatActions} from "~/modules/x-chat";

    export default {
        data() {
            return {
                name: "",
                text: ""
            }
        },
        methods: {
            onSubmit(event) {
                event.preventDefault();

                store.dispatch(
                    xChatActions.sendMessage(
                        this.name + "(vue)",
                        this.text,
                        "right",
                    ),
                );

                this.text = "";
            }
        }
    }
</script>

// src/demo/modules/x-chat/components/chat-client.svelte
<script>
    import {store} from "~/demo/store";
    import {xChatActions} from "~/demo/modules/x-chat";

    function handleSubmit(event) {
        event.preventDefault();

        store.dispatch(
            xChatActions.sendMessage(
                name + "(svelte)",
                text,
            )
        );

        text = ""
    }

    let name = "";
    let text = "";
</script>

<form class="chat-form" on:submit={handleSubmit} >
    <div class="form-group">
        <label for="name">name:</label>
        <input
            id="name"
            type="text"
            class="form-control"
            bind:value={name}
            required
        >
    </div>
    <div class="form-group" >
        <label for="text">text</label>
        <textarea
            name="text"
            id="text"
            cols="30"
            rows="10"
            class="form-control"
            bind:value={text}
            required
        ></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
